# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=1)),
                ('direccion', models.CharField(max_length=40)),
                ('latitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=22)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_repeticion', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.IntegerField(default=1)),
                ('cantidad_disponible', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=128)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('descripcion', models.TextField(max_length=400)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=128)),
                ('portada', models.ImageField(upload_to='libros_images/')),
                ('descripcion', models.TextField(max_length=400)),
                ('url', models.URLField(blank=True, null=True)),
                ('generos', models.ManyToManyField(related_name='generos_libro', to='lectur_app.Genero')),
                ('likes', models.ManyToManyField(related_name='likes_libro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=400)),
                ('imagen', models.ImageField(upload_to='talleres_images/')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cupos', models.IntegerField(default=0)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Lector')),
                ('participantes', models.ManyToManyField(related_name='participantes_taller', to='lectur_app.Lector')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo_Escrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField(max_length=400)),
                ('texto', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Lector')),
                ('generos', models.ManyToManyField(related_name='generos_escrito', to='lectur_app.Genero')),
                ('likes', models.ManyToManyField(related_name='likes_escrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(blank=True, max_length=400)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Lector')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo_escrito',
            name='valoraciones',
            field=models.ManyToManyField(related_name='valoraciones_escrito', to='lectur_app.Valoracion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='valoraciones',
            field=models.ManyToManyField(related_name='valoraciones_libro', to='lectur_app.Valoracion'),
        ),
        migrations.AddField(
            model_name='info_libro',
            name='lectuales',
            field=models.ManyToManyField(related_name='lectores_actuales', to='lectur_app.Lector'),
        ),
        migrations.AddField(
            model_name='info_libro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Libro'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='administradores',
            field=models.ManyToManyField(related_name='administradores_comunidad', to='lectur_app.Lector'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='bibliotecas_amigas',
            field=models.ManyToManyField(related_name='biblioteca_amiga', to='lectur_app.Biblioteca'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='libros',
            field=models.ManyToManyField(related_name='libros_comunidad', to='lectur_app.Info_Libro'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='lugares_encuentro',
            field=models.ManyToManyField(related_name='lugares_encuentro', to='lectur_app.Espacio'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes_comunidad', to='lectur_app.Lector'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='talleres',
            field=models.ManyToManyField(related_name='talleres_comunidad', to='lectur_app.Taller'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='administradores',
            field=models.ManyToManyField(related_name='administradores_biblioteca', to='lectur_app.Lector'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='espacios',
            field=models.ManyToManyField(related_name='espacios_bibliotecas', to='lectur_app.Espacio'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='libros',
            field=models.ManyToManyField(related_name='libros_biblioteca', to='lectur_app.Info_Libro'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='programacion',
            field=models.ManyToManyField(related_name='programacion_biblioteca', to='lectur_app.Evento'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Espacio'),
        ),
    ]
