# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0002_auto_20170227_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='comunidades_images/'),
        ),
    ]
