# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0004_auto_20170307_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
