# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0005_auto_20170307_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(default='_', max_length=20),
            preserve_default=False,
        ),
    ]
