# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0006_comunidad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
