# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0007_auto_20170307_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Espacio'),
        ),
    ]
