# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0009_auto_20170316_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tema',
            field=models.ManyToManyField(blank=True, related_name='tema_foro', to='lectur_app.Tema'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foro',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='categoria_foro', to='lectur_app.Categoria'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='mensaje',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='respuesta',
            field=models.ManyToManyField(blank=True, related_name='respuesta_tema', to='lectur_app.Respuesta'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='valoracion',
            field=models.ManyToManyField(blank=True, related_name='valoracion_tema', to='lectur_app.Valoracion'),
        ),
    ]
