# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0010_auto_20170322_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='autor',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Lector'),
        ),
    ]
