# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0011_auto_20170323_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectur_app.Lector'),
        ),
    ]
