# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0014_auto_20170329_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='latitud',
            field=models.DecimalField(decimal_places=30, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='longitud',
            field=models.DecimalField(decimal_places=30, default=0.0, max_digits=40),
        ),
    ]
