# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0016_reto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='cantidad_minima',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='premio',
            name='lista_ganadores',
            field=models.ManyToManyField(blank=True, related_name='ganadores_premio', to='lectur_app.Lector'),
        ),
    ]
