# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0018_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero_literario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('comunidades', models.ManyToManyField(blank=True, related_name='genero_comunidades', to='lectur_app.Comunidad')),
                ('temas', models.ManyToManyField(blank=True, related_name='genero_tema_foro', to='lectur_app.Tema')),
            ],
        ),
    ]
