# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur_app', '0020_felicitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=50)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
